name: stroll_test
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter

  #UI
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.9
  flutter_screenutil: ^5.9.3

  #DEPENDENCY INJECTION
  get_it: ^7.6.4
  provider: ^6.1.1

  #ANNOTATION AND MODELLING
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

  #NAVIGATION
  go_router: 12.1.3

  #LOGGING
  logger: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^4.0.0

  #ANNOTATION
  build_runner: ^2.4.7
  flutter_gen_runner:
  freezed: ^2.4.6
  json_serializable: ^6.7.1

flutter_gen:
  output: lib/core/gen/
  assets:
    enabled: true
    outputs:
      class_name: StrollAssets
      package_parameter_enabled: false
  fonts:
    outputs:
      class_name: StrollFonts
      package_parameter_enabled: false
  colors:
    outputs:
      class_name: StrollColors
    inputs:
      - assets/colors/colors.xml
  integrations:
    flutter_svg: true



flutter:
  uses-material-design: true

  fonts:
    - family: Proxima Nova
      fonts:
        - asset: assets/fonts/Proxima Nova/Proxima Nova Black.otf
          weight: 800
        - asset: assets/fonts/Proxima Nova/Proxima Nova Black Italic.otf
          weight: 800
          style: italic
        - asset: assets/fonts/Proxima Nova/Proxima Nova Extrabold.otf
          weight: 700
        - asset: assets/fonts/Proxima Nova/Proxima Nova Extrabold Italic.otf
          weight: 700
          style: italic
        - asset: assets/fonts/Proxima Nova/Proxima Nova Bold.otf
          weight: 600
        - asset: assets/fonts/Proxima Nova/Proxima Nova Bold Italic.otf
          weight: 600
          style: italic
        - asset: assets/fonts/Proxima Nova/Proxima Nova Semibold.otf
          weight: 500
        - asset: assets/fonts/Proxima Nova/Proxima Nova Semibold Italic.otf
          weight: 500
          style: italic
        - asset: assets/fonts/Proxima Nova/Proxima Nova Regular.otf
          weight: 400
        - asset: assets/fonts/Proxima Nova/Proxima Nova Thin.otf
          weight: 300
        - asset: assets/fonts/Proxima Nova/Proxima Nova Thin Italic.otf
          weight: 300
          style: italic

    
  assets:
    - assets/images/svg/
    - assets/images/png/
