name: Blue personal jobs
on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  flutter_test:
    name: Run flutter test and analyze
    runs-on: ubuntu-latest
    steps:
      # Setup Java environment in order to build the Android app.
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: "11"
          cache: "gradle"

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable" # 'dev', 'alpha', default to: 'stable'
          flutter-version: 3.22.2
          cache: true
      - run: flutter --version

      - name: Get Branch Name
        id: branch
        # run: echo "::set-output name=branch::${GITHUB_REF##*/}"
        run: echo "{name}={branch}" >> ${GITHUB_REF##*/}

        # flutter clean
      - run: flutter clean
        # Get flutter dependencies.
      - run: flutter pub get
        # Statically analyze the flutter codebase for any errors.
      - run: flutter analyze .

